#!/usr/bin/env bash
# Lamplight: put the CLI on PATH, wire the theme hook, start the effect unit.
#
# `omarchy plugin add` already placed this whole repo in your plugins
# directory, and the bar widget calls bin/govee-lamp relative to itself, so the
# widget works without this script. Run it to get the CLI on your PATH and the
# background effects running.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="${XDG_BIN_HOME:-$HOME/.local/bin}"
HOOKS="$HOME/.config/omarchy/hooks/theme-set.d"
UNITS="$HOME/.config/systemd/user"

mkdir -p "$BIN" "$HOOKS" "$UNITS"

ln -sfn "$HERE/bin/govee-lamp" "$BIN/govee-lamp"
echo "cli      -> $BIN/govee-lamp"

# The hook is generated rather than copied so it points at THIS checkout.
cat > "$HOOKS/50-govee-lamp" <<HOOK
#!/bin/bash
# Keep the Govee fleet in step with the Omarchy theme.
# Detached and silent: a sleeping lamp must never stall a theme switch.
# Generated by lamplight/install.sh
LAMP="$HERE/bin/govee-lamp"
[[ -x \$LAMP ]] || exit 0
setsid "\$LAMP" theme >/dev/null 2>&1 </dev/null &
exit 0
HOOK
chmod +x "$HOOKS/50-govee-lamp"
echo "hook     -> $HOOKS/50-govee-lamp"

sed "s|^ExecStart=.*|ExecStart=$HERE/bin/govee-lamp run|" \
    "$HERE/systemd/govee-lamp.service" > "$UNITS/govee-lamp.service"
systemctl --user daemon-reload
echo "unit     -> $UNITS/govee-lamp.service"

cat <<'NEXT'

Two things this script cannot do for you:

1. Turn LAN Control ON for each device in the Govee Home app. Every Govee unit
   ships with it off and silently drops every packet until you do. It answers
   ping the whole time, so it looks alive and is not reachable.

2. Allow the replies through your firewall. Commands are one-way UDP out, but
   replies arrive on port 4002 as a fresh flow that conntrack will not class as
   RELATED, so a default-deny firewall eats them and everything reports SILENT
   while the lights still change. On ufw:

     sudo ufw allow from 192.168.0.0/16 to any port 4002 proto udp

Then:
     govee-lamp devices scan
     govee-lamp mode mix
     systemctl --user enable --now govee-lamp
NEXT
